### ISSUE TITLE
unexcepted args

### ISSUE THREAD

**Issue by kimpty** [YapengTian/AV-Robustness-CVPR21#4]
main_attack.py line 550
builder.build_sound  builder.build_frame 
fc_dim is unexcepted args, i delete and it worked well ,should i delete it?

**Comment by YapengTian** [comment]
Yes, it should be deleted. Please check the latest code and new readme in the repo. I have fixed the issues in the previous version.

**Comment by YapengTian** [comment]
For re-producing defense results on the MUSIC dataset, please follow the suggestion in the readme: first combine the MinSim loss to train the av event recognition model (uncomment the loss term in the L468 of main_attack.py ) and then train the defense model. 

Please let me know if you have any questions.

**Comment by kimpty** [comment]
Thank you. I'm sorry. I didn't see the new version just now. I still use the previous version just now.

**Comment by YapengTian** [comment]
No problem. I should fix these problems earlier. I tried to clean the previous dirty code but forgot to fix the issues.
